# Generated by Django 5.2.7 on 2025-10-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Bashliq')),
                ('text', models.TextField(max_length=10000, verbose_name='Metn')),
                ('image', models.ImageField(upload_to='', verbose_name='Shekil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradilma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenileme Tarixi')),
            ],
            options={
                'verbose_name': 'Blog yazisi',
                'verbose_name_plural': 'Blog Yazilari',
                'ordering': ['-id'],
            },
        ),
    ]
